<?php

namespace W4H\Bundle\EventTaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function withTaskOwners($starts_at, $filters = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select(array('task', 'owners', 'person', 'role'))
           ->from('W4HEventTaskBundle:Task', 'task')
           ->leftJoin('task.owners', 'owners')
           ->leftJoin('owners.person', 'person')
           ->leftJoin('owners.role', 'role')
           ->where($qb->expr()->eq($qb->expr()->substring('task.starts_at', 1, 10), ':starts_at'))
           ->setParameter('starts_at', $starts_at);

        if(!empty($filters['locations'][0]))
        {
            $ids = array();
            foreach($filters['locations'] as $location)
                $ids[] = $location->getId();

            $qb->andWhere($qb->expr()->in('task.location', $ids));
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
