<?php

namespace W4H\Bundle\PaperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaperPresenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaperPresenterRepository extends EntityRepository
{
}