<?php

namespace W4H\Bundle\PaperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaperRepository extends EntityRepository
{
    /**
     * Get all papers ordered by title ASC query builder
     *
     * @return DoctrineQueryBuilder
     */
    public function findAllOrderedByTitleQueryBuilder()
    {
        return $this->createQueryBuilder('p')->orderBy('p.title', 'ASC');
    }

    /**
     * Get all papers ordered by title ASC query
     *
     * @return DoctrineQuery
     */
    public function findAllOrderedByTitleQuery()
    {
        return $this->findAllOrderedByTitleQueryBuilder()->getQuery();
    }

    /**
     * Get all papers ordered by title ASC
     *
     * @return Collection User
     */
    public function findAllOrderedByTitle()
    {
        return $this->findAllOrderedByTitleQuery()->getResult();
    }
}
