imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:       ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# W4H calendar configuration
w4h_calendar:
    schedule_start: 8
    schedule_limit: 19
    schedule_step: 15
    schedule_default_year: 2012
    schedule_default_month: 4
    schedule_default_day: 16
    schedule_row_height: 14
    schedule_column_width: 100

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: ~

#        entity_managers:
#            default:
#                mappings:
#                    FOSUserBundle:    ~
#                    W4HUserBundle:    ~
#                    SonataUserBundle: ~

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class:       W4H\Bundle\UserBundle\Entity\Person
    group:
        group_class:  W4H\Bundle\UserBundle\Entity\Group
    registration:
        form:
            type: w4h_user_profile

sonata_user:
    security_acl:     true
    class:
        user:         W4H\Bundle\UserBundle\Entity\Person
        group:        W4H\Bundle\UserBundle\Entity\Group

parameters:
    sonata.user.admin.user.class: W4H\Bundle\UserBundle\Admin\Entity\UserAdmin

sonata_admin:
#    security_handler: sonata.admin.security.handler.noop
#    sonata.admin.security.handler.acl

    title:      W4H Project
    title_logo: /images/logo.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
#    dashboard_groups:
#        default: ~

    dashboard:
        blocks:
            # display a dashboard block
            - { position: right, type: sonata.admin.block.admin_list }

            # Customize this part to add new block configuration
            #- { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the Sonata Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):"} }
            #- { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

services:
    twig.extension.slugify:
        class: W4H\Bundle\CalendarBundle\Extension\SlugifyTwigExtension
        tags:
            -  { name: twig.extension }
    twig.extension.country:
        class: W4H\Bundle\CalendarBundle\Extension\CountryTwigExtension
        tags:
            -  { name: twig.extension }
    twig.extension.date:
        class: W4H\Bundle\CalendarBundle\Extension\DateTwigExtension
        arguments:
            - @router
        tags:
            -  { name: twig.extension }
