W4HCalendarBundle:
    resource: "@W4HCalendarBundle/Controller/"
    type:     annotation
    prefix:   /

W4HLocationBundle:
    resource: "@W4HLocationBundle/Controller/"
    type:     annotation
    prefix:   /admin

W4HEventTaskBundle:
    resource: "@W4HEventTaskBundle/Controller/"
    type:     annotation
    prefix:   /admin

W4HUserBundle:
    resource: "@W4HUserBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /admin/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /admin/profile

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
