<?php
namespace W4H\Bundle\LocationBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use W4H\Bundle\LocationBundle\Entity\Location;

class LoadLocationData implements FixtureInterface
{
    public function load(ObjectManager $manager)
    {
        $location = new Location();
        $location->setName('Salle Bellecour 1');
        $location->setBuilding('Nouveau');
        $location->setLevel('Accueil Bellecour');
        $location->setClassRoomPlaces(56);
        $location->setConferenceRoomPlaces(125);
        $location->setStandingRoomPlaces(130);
        $location->setVideoProjector(true);
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salle Bellecour 2');
        $location->setBuilding('Nouveau');
        $location->setLevel('Accueil Bellecour');
        $location->setClassRoomPlaces(84);
        $location->setConferenceRoomPlaces(154);
        $location->setStandingRoomPlaces(130);
        $location->setVideoProjector(true);
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salle Bellecour 3');
        $location->setBuilding('Nouveau');
        $location->setLevel('Accueil Bellecour');
        $location->setClassRoomPlaces(68);
        $location->setConferenceRoomPlaces(105);
        $location->setStandingRoomPlaces(120);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Foyers Forum 4, 5 & 6');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Forum');
        $location->setClassRoomPlaces(0);
        $location->setConferenceRoomPlaces(0);
        $location->setStandingRoomPlaces(1300);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Forum 4');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Forum');
        $location->setClassRoomPlaces(768);
        $location->setConferenceRoomPlaces(1297);
        $location->setStandingRoomPlaces(1150);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Forum 5');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Forum');
        $location->setClassRoomPlaces(632);
        $location->setConferenceRoomPlaces(1082);
        $location->setStandingRoomPlaces(1000);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Forum 6');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Forum');
        $location->setClassRoomPlaces(768);
        $location->setConferenceRoomPlaces(1190);
        $location->setStandingRoomPlaces(1150);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salle Tête d\'Or 1');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Tête d\'Or');
        $location->setClassRoomPlaces(46);
        $location->setConferenceRoomPlaces(99);
        $location->setStandingRoomPlaces(80);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salle Tête d\'Or 2');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Tête d\'Or');
        $location->setClassRoomPlaces(48);
        $location->setConferenceRoomPlaces(99);
        $location->setStandingRoomPlaces(90);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salle Tête d\'Or 1+2');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Tête d\'Or');
        $location->setClassRoomPlaces(116);
        $location->setConferenceRoomPlaces(192);
        $location->setStandingRoomPlaces(170);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salon Tête d\'Organization');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Tête d\'Or');
        $location->setClassRoomPlaces(88);
        $location->setConferenceRoomPlaces(180);
        $location->setStandingRoomPlaces(150);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salle Gratte-Ciel 1');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Gratte-Ciel');
        $location->setClassRoomPlaces(38);
        $location->setConferenceRoomPlaces(100);
        $location->setStandingRoomPlaces(80);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salle Gratte-Ciel 2');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Gratte-Ciel');
        $location->setClassRoomPlaces(54);
        $location->setConferenceRoomPlaces(115);
        $location->setStandingRoomPlaces(90);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salle Gratte-Ciel 3');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Gratte-Ciel');
        $location->setClassRoomPlaces(42);
        $location->setConferenceRoomPlaces(84);
        $location->setStandingRoomPlaces(80);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salle Gratte-Ciel 1+2+3');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Gratte-Ciel');
        $location->setClassRoomPlaces(180);
        $location->setConferenceRoomPlaces(330);
        $location->setStandingRoomPlaces(240);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Foyer Gratte-Ciel Rhône');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Gratte-Ciel');
        $location->setClassRoomPlaces(0);
        $location->setConferenceRoomPlaces(50);
        $location->setStandingRoomPlaces(250);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Foyer Gratte-Ciel Parc');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Gratte-Ciel');
        $location->setClassRoomPlaces(0);
        $location->setConferenceRoomPlaces(50);
        $location->setStandingRoomPlaces(250);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Foyer Gratte-Ciel Prestige');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Gratte-Ciel');
        $location->setClassRoomPlaces(0);
        $location->setConferenceRoomPlaces(0);
        $location->setStandingRoomPlaces(0);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Salon Prestige Gratte-Ciel');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Gratte-Ciel');
        $location->setClassRoomPlaces(88);
        $location->setConferenceRoomPlaces(168);
        $location->setStandingRoomPlaces(150);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $location = new Location();
        $location->setName('Grand Salon Prestige Gratte-Ciel');
        $location->setBuilding('Nouveau');
        $location->setLevel('Niveau Gratte-Ciel');
        $location->setClassRoomPlaces(154);
        $location->setConferenceRoomPlaces(288);
        $location->setStandingRoomPlaces(200);
        $location->setVideoProjector('');
        $location->setSound(false);
        $location->setInternet(false);
        $location->setOtherDevices('');
        $location->setAccessibility(2);
        $location->setLatitude('');
        $location->setLongitude('');
        $manager->persist($location);

        $manager->flush();
    }
}
